version: 1
config:
  version: 1
app:
  name: ${APP_NAME:my-service}
  env: ${APP_ENV:dev}
  tz_store: UTC
  tz_render: ${LOG_RENDER_TZ:Europe/London}
runtime:
  tz: UTC
io:
  root: /var/run/app
  retry: 3
limits:
  rate: 100
  concurrency: 16
db:
  host: 127.0.0.1
  port: 5432
secrets:
  db_password: env:DB_PASS
logger:
  level: ${LOG_LEVEL:INFO}
  namespace: ${LOG_NAMESPACE:cad.tabpfn}
  timezone:
    render: ${LOG_RENDER_TZ:Europe/London}
  sinks:
    - type: console
      stream: stdout
    - type: rotating_file
      path: ${LOG_FILE_PATH:logs/app.log}
      max_bytes: ${LOG_FILE_MAX_BYTES:10485760}
      backups: ${LOG_FILE_BACKUPS:5}
  sampling:
    default_rate: ${LOG_SAMPLING_DEFAULT:1.0}
    seed: ${LOG_SAMPLING_SEED:42}
    rules:
      - level: DEBUG
        rate: ${LOG_SAMPLING_DEBUG_RATE:0.1}
        burst: 5
        interval: 60
  redact:
    allow:
      - trace_id
      - span_id
      - corr_id
    deny_patterns:
      - password
      - secret
      - token
      - key
      - credential
      - pwd
task_system:
  pool:
    default_ttl: 120.0
    backend:
      type: memory
  executor:
    max_concurrency: 4
    lease_batch_size: 10
    lease_ttl: 30.0
    prefetch: 20
    idle_sleep: 0.5
    max_retries: 2
    backoff_base: 0.5
    backoff_jitter: 0.3
    task_timeout: null
    rate_limit_per_sec: null
    rate_limit_burst: null
    failure_delay: null
    filters: {}
    requeue_on_failure: true

pipelines:
  s2:
    sources:
      - dataset: MFInstSeg
        tier: gold
        root: ${S2_MFINSTSEG_ROOT:./data/MFInstSeg}
        pattern: "**/*"
        allowed_extensions: [".step", ".stp", ".stpz", ".brep", ".brp"]
      - dataset: MFCAD
        tier: silver
        root: ${S2_MFCAD_ROOT:./data/MFCAD}
        pattern: "**/*"
        allowed_extensions: [".step", ".stp", ".stpz", ".brep", ".brp"]
    sampling:
      subset_n: null
      subset_frac: null
      seed: 42
    features:
      descriptor_length: 64
      sample_points: 4096
      random_seed: 1337
    dedup:
      similarity_threshold: 0.995
      bbox_tolerance: 0.02
    clustering:
      method: dbscan
      eps: 0.012
      min_samples: 6
      auto_eps:
        enabled: true
        quantile: 0.12
        sample_size: 20000
        scale: 1.02
    partition:
      strategy: weighted
      constraints:
        max_items_per_task: 128
        shuffle_seed: 42
    outputs:
      root: ${S2_OUTPUT_ROOT:./data/s2_out}
      signatures_file: signatures.parquet
      part_index_file: part_index.csv
      part_index_for_split_file: part_index.for_split.csv
      family_hist_file: family_hist.csv
      diagnostics_file: diagnostics.json
      write_signatures: true
    quarantine:
      preferred_tier: gold
      reason: cross_tier_duplicate

